create extension if not exists pgcrypto;
create table if not exists exercises(id uuid primary key default gen_random_uuid(),day_no int not null,sort_order int not null,name text not null,increment_kg numeric(6,2) default 2.5,default_weight numeric(6,2) default 0,active boolean default true);
create table if not exists workouts(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,workout_day int not null,performed_at timestamptz default now());
create table if not exists workout_sets(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,workout_id uuid not null references workouts(id) on delete cascade,exercise_id uuid not null references exercises(id),set_no int not null,weight_kg numeric(6,2) default 0,reps int default 0,created_at timestamptz default now());
alter table exercises enable row level security; alter table workouts enable row level security; alter table workout_sets enable row level security;
create policy "read exercises" on exercises for select to authenticated using(true);
create policy "own workouts" on workouts for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own sets" on workout_sets for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
insert into exercises(day_no,sort_order,name,increment_kg) values
(1,1,'Barbell Bench Press',2.5),(1,2,'Incline Barbell Bench Press',2.5),(1,3,'Dips',1),(1,4,'Dumbbell Fly',2),(1,5,'Cable Pushdown',2.5),(1,6,'Cable Rope Pushdown',2.5),(1,7,'Dumbbell Kickback',2),
(2,1,'Lat Pulldown',2.5),(2,2,'Close Grip Pulldown',2.5),(2,3,'Cable Row',2.5),(2,4,'Lower Back Extension',2.5),(2,5,'Barbell Curl',2.5),(2,6,'Dumbbell Hammer Curl',2),
(3,1,'Dumbbell Shoulder Press',2),(3,2,'Dumbbell Lateral Raise',1),(3,3,'Plate Front Raise',2.5),(3,4,'Face Pull',2.5),(3,5,'Shrugs',2.5),(3,6,'Dumbbell Squat',2),(3,7,'Dumbbell Lunges',2),(3,8,'Leg Extension',2.5),(3,9,'Leg Curl',2.5),(3,10,'Adductor Machine',2.5);
create or replace function get_exercises_with_last_session(p_day_no int) returns table(id uuid,day_no int,sort_order int,name text,increment_kg numeric,default_weight numeric,last_weight numeric,last_reps int[],previous_weight numeric,last_increase_at timestamptz) language sql security invoker as $$
with s as(select ws.exercise_id,w.id wid,w.performed_at,max(ws.weight_kg) weight,array_agg(ws.reps order by ws.set_no) reps,dense_rank() over(partition by ws.exercise_id order by w.performed_at desc) rk from workout_sets ws join workouts w on w.id=ws.workout_id where w.user_id=auth.uid() group by ws.exercise_id,w.id,w.performed_at), lt as(select exercise_id,max(weight) filter(where rk=1) last_weight,max(reps) filter(where rk=1) last_reps,max(weight) filter(where rk=2) previous_weight from s where rk<=2 group by exercise_id), inc as(select exercise_id,max(performed_at) last_increase_at from(select exercise_id,performed_at,weight,lag(weight) over(partition by exercise_id order by performed_at) prev from s)x where weight>prev group by exercise_id) select e.id,e.day_no,e.sort_order,e.name,e.increment_kg,e.default_weight,lt.last_weight,lt.last_reps,lt.previous_weight,inc.last_increase_at from exercises e left join lt on lt.exercise_id=e.id left join inc on inc.exercise_id=e.id where e.day_no=p_day_no and e.active=true order by e.sort_order; $$;
